import type { UserRole } from '../../generated/prisma/client.js'

export interface PermissionDef {
  resource: string
  action: string
  description: string
}

export const ALL_PERMISSIONS: PermissionDef[] = [
  { resource: 'users', action: 'create', description: 'Create users' },
  { resource: 'users', action: 'read', description: 'View users' },
  { resource: 'users', action: 'update', description: 'Update users' },
  { resource: 'users', action: 'delete', description: 'Delete users' },
  { resource: 'companies', action: 'create', description: 'Create companies' },
  { resource: 'companies', action: 'read', description: 'View companies' },
  { resource: 'companies', action: 'update', description: 'Update companies' },
  { resource: 'companies', action: 'delete', description: 'Delete companies' },
  { resource: 'projects', action: 'create', description: 'Create projects' },
  { resource: 'projects', action: 'read', description: 'View projects' },
  { resource: 'projects', action: 'update', description: 'Update projects' },
  { resource: 'projects', action: 'delete', description: 'Delete projects' },
  { resource: 'tasks', action: 'create', description: 'Create tasks' },
  { resource: 'tasks', action: 'read', description: 'View tasks' },
  { resource: 'tasks', action: 'update', description: 'Update tasks' },
  { resource: 'tasks', action: 'delete', description: 'Delete tasks' },
  { resource: 'tickets', action: 'create', description: 'Create tickets' },
  { resource: 'tickets', action: 'read', description: 'View tickets' },
  { resource: 'tickets', action: 'update', description: 'Update tickets' },
  { resource: 'tickets', action: 'delete', description: 'Delete tickets' },
  { resource: 'invoices', action: 'create', description: 'Create invoices' },
  { resource: 'invoices', action: 'read', description: 'View invoices' },
  { resource: 'invoices', action: 'update', description: 'Update invoices' },
  { resource: 'invoices', action: 'delete', description: 'Delete invoices' },
  { resource: 'contracts', action: 'read', description: 'View contracts' },
  { resource: 'contracts', action: 'create', description: 'Create contracts' },
  { resource: 'contracts', action: 'update', description: 'Update contracts' },
  { resource: 'leads', action: 'create', description: 'Create leads' },
  { resource: 'leads', action: 'read', description: 'View leads' },
  { resource: 'leads', action: 'update', description: 'Update leads' },
  { resource: 'leads', action: 'delete', description: 'Delete leads' },
  { resource: 'proposals', action: 'create', description: 'Create proposals' },
  { resource: 'proposals', action: 'read', description: 'View proposals' },
  { resource: 'proposals', action: 'update', description: 'Update proposals' },
  { resource: 'reports', action: 'read', description: 'View reports' },
  { resource: 'audit_logs', action: 'read', description: 'View audit logs' },
  { resource: 'announcements', action: 'create', description: 'Create announcements' },
  { resource: 'announcements', action: 'read', description: 'View announcements' },
  { resource: 'knowledge_base', action: 'create', description: 'Create KB articles' },
  { resource: 'knowledge_base', action: 'read', description: 'View KB articles' },
  { resource: 'knowledge_base', action: 'update', description: 'Update KB articles' },
  { resource: 'files', action: 'create', description: 'Upload files' },
  { resource: 'files', action: 'read', description: 'View files' },
  { resource: 'files', action: 'delete', description: 'Delete files' },
  { resource: 'time_entries', action: 'create', description: 'Create time entries' },
  { resource: 'time_entries', action: 'read', description: 'View time entries' },
  { resource: 'time_entries', action: 'update', description: 'Update time entries' },
  { resource: 'calendar', action: 'create', description: 'Create calendar events' },
  { resource: 'calendar', action: 'read', description: 'View calendar events' },
  { resource: 'goals', action: 'create', description: 'Create goals' },
  { resource: 'goals', action: 'read', description: 'View goals' },
  { resource: 'goals', action: 'update', description: 'Update goals' },
  { resource: 'jobs', action: 'create', description: 'Create job postings' },
  { resource: 'jobs', action: 'read', description: 'View job postings' },
  { resource: 'jobs', action: 'update', description: 'Update job postings' },
  { resource: 'jobs', action: 'delete', description: 'Delete job postings' },
  { resource: 'job_applications', action: 'read', description: 'View job applications' },
  { resource: 'job_applications', action: 'update', description: 'Update job applications' },
]

export const ROLE_PERMISSIONS: Record<string, { resource: string; action: string }[]> = {
  LANTERN_STAFF: [
    { resource: 'users', action: 'read' },
    { resource: 'companies', action: 'read' },
    { resource: 'projects', action: 'create' }, { resource: 'projects', action: 'read' }, { resource: 'projects', action: 'update' },
    { resource: 'tasks', action: 'create' }, { resource: 'tasks', action: 'read' }, { resource: 'tasks', action: 'update' },
    { resource: 'tickets', action: 'read' }, { resource: 'tickets', action: 'update' },
    { resource: 'leads', action: 'create' }, { resource: 'leads', action: 'read' }, { resource: 'leads', action: 'update' },
    { resource: 'proposals', action: 'create' }, { resource: 'proposals', action: 'read' }, { resource: 'proposals', action: 'update' },
    { resource: 'contracts', action: 'read' },
    { resource: 'invoices', action: 'create' }, { resource: 'invoices', action: 'read' }, { resource: 'invoices', action: 'update' },
    { resource: 'reports', action: 'read' },
    { resource: 'announcements', action: 'read' },
    { resource: 'knowledge_base', action: 'create' }, { resource: 'knowledge_base', action: 'read' }, { resource: 'knowledge_base', action: 'update' },
    { resource: 'files', action: 'create' }, { resource: 'files', action: 'read' },
    { resource: 'time_entries', action: 'create' }, { resource: 'time_entries', action: 'read' }, { resource: 'time_entries', action: 'update' },
    { resource: 'calendar', action: 'create' }, { resource: 'calendar', action: 'read' },
    { resource: 'goals', action: 'read' },
    { resource: 'jobs', action: 'read' },
    { resource: 'job_applications', action: 'read' }, { resource: 'job_applications', action: 'update' },
  ],
  PROJECT_MANAGER: [
    { resource: 'projects', action: 'create' }, { resource: 'projects', action: 'read' }, { resource: 'projects', action: 'update' },
    { resource: 'tasks', action: 'create' }, { resource: 'tasks', action: 'read' }, { resource: 'tasks', action: 'update' }, { resource: 'tasks', action: 'delete' },
    { resource: 'tickets', action: 'read' }, { resource: 'tickets', action: 'update' },
    { resource: 'companies', action: 'read' },
    { resource: 'users', action: 'read' },
    { resource: 'reports', action: 'read' },
    { resource: 'files', action: 'create' }, { resource: 'files', action: 'read' },
    { resource: 'time_entries', action: 'create' }, { resource: 'time_entries', action: 'read' }, { resource: 'time_entries', action: 'update' },
    { resource: 'calendar', action: 'create' }, { resource: 'calendar', action: 'read' },
    { resource: 'knowledge_base', action: 'read' },
    { resource: 'announcements', action: 'read' },
  ],
  SUPPORT_AGENT: [
    { resource: 'tickets', action: 'create' }, { resource: 'tickets', action: 'read' }, { resource: 'tickets', action: 'update' },
    { resource: 'companies', action: 'read' },
    { resource: 'users', action: 'read' },
    { resource: 'projects', action: 'read' },
    { resource: 'knowledge_base', action: 'create' }, { resource: 'knowledge_base', action: 'read' }, { resource: 'knowledge_base', action: 'update' },
    { resource: 'files', action: 'create' }, { resource: 'files', action: 'read' },
    { resource: 'announcements', action: 'read' },
    { resource: 'time_entries', action: 'create' }, { resource: 'time_entries', action: 'read' },
  ],
  FINANCE_MANAGER: [
    { resource: 'invoices', action: 'create' }, { resource: 'invoices', action: 'read' }, { resource: 'invoices', action: 'update' }, { resource: 'invoices', action: 'delete' },
    { resource: 'contracts', action: 'create' }, { resource: 'contracts', action: 'read' }, { resource: 'contracts', action: 'update' },
    { resource: 'companies', action: 'read' },
    { resource: 'users', action: 'read' },
    { resource: 'projects', action: 'read' },
    { resource: 'reports', action: 'read' },
    { resource: 'goals', action: 'create' }, { resource: 'goals', action: 'read' }, { resource: 'goals', action: 'update' },
    { resource: 'announcements', action: 'read' },
  ],
  CLIENT_ADMIN: [
    { resource: 'users', action: 'read' }, { resource: 'users', action: 'create' }, { resource: 'users', action: 'update' },
    { resource: 'projects', action: 'read' },
    { resource: 'tasks', action: 'read' },
    { resource: 'tickets', action: 'create' }, { resource: 'tickets', action: 'read' },
    { resource: 'invoices', action: 'read' },
    { resource: 'contracts', action: 'read' },
    { resource: 'reports', action: 'read' },
    { resource: 'announcements', action: 'read' },
    { resource: 'knowledge_base', action: 'read' },
    { resource: 'files', action: 'create' }, { resource: 'files', action: 'read' },
  ],
  CLIENT_USER: [
    { resource: 'projects', action: 'read' },
    { resource: 'tasks', action: 'read' },
    { resource: 'tickets', action: 'create' }, { resource: 'tickets', action: 'read' },
    { resource: 'invoices', action: 'read' },
    { resource: 'announcements', action: 'read' },
    { resource: 'knowledge_base', action: 'read' },
    { resource: 'files', action: 'read' },
  ],
}
